blueprint:
  name: Motion-activated Scene after Sunset
  description: Turn on scene when motion is detected and it's after Sunset.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupied
    scene_target:
      name: Scene
      selector:
        target:
          entity:
            domain: scene
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: sun
    before: sunrise
    after: sunset

action:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.back_garden_bright

  - service: light.turn_on
    target: !input scene_target
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: !input scene_target